# MADE BY:
#  __    __                                          __        __  __  __                     
# /  |  /  |                                        /  |      /  |/  |/  |                    
# $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
# $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#  $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#   $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
# $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
# $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                         $$ |                                      /  \__$$ |
#                                         $$ |                                      $$    $$/
#                                         $$/                                        $$$$$$/
VERSION: "1.1.0" # Internal use only

# This is the max allowed enchanting level with the command in-game
# Minecraft: Bedrock Edition has a maximum of 32767 enchantment levels
Max-Level: 5000

# Here you can specify enchantment broadcast message settings
Broadcast:

  # Choose who should receive the broadcast messages
  # Options are sender, target, console
  # Add any number of recipients to this key
  # Leave blank if you want no broadcasts
  SendTo:
  - "sender"
  - "console"

  # This is the message that will be broadcasted to the selected recipients
  # Available tags are:
  # {name} → name of enchantment
  # {level} → level of enchantment
  # {target} → recipient player
  # {sender} → command provoker
  Message: "§a{sender} added §b{name} §alevel §b{level} §afor {target}"

Command:

  # This is name of the command that will be executed to use the plugin
  Name: "/enchant"

  # This is the command's description shown in the command window
  Description: "Enchant items up to level 5000"

  Permission:

    # Choose whether to require users to have permission to execute the command
    Enabled: false

    # This is the command's usage permission
    Node: "maxenchants.enchant"

  # This is an option to override an existing command with the one from MaxEnchants
  # Keeping this true makes sure that there are not two types of the same command
  Override: true